Question-1


In [1]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

print("Original array:", arr)
print("Addition of 2:", arr + 2)
print("Multiply by 3:", arr * 3)
print("Divide by 2:", arr / 2)

Original array: [1 2 3 4 5]
Addition of 2: [3 4 5 6 7]
Multiply by 3: [ 3  6  9 12 15]
Divide by 2: [0.5 1.  1.5 2.  2.5]


Question-2

In [2]:
import numpy as np

arr = np.array([1, 2, 3, 6, 4, 5])
print("Reversed array:", arr[::-1])

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
x_values, x_counts = np.unique(x, return_counts=True)
x_max = np.max(x_counts)
x_frequent = x_values[x_counts == x_max]

print("Most frequent value(s) in x:", x_frequent)
for value in x_frequent:
    print("Indices:", np.where(x == value)[0])

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])
y_values, y_counts = np.unique(y, return_counts=True)
y_max = np.max(y_counts)
y_frequent = y_values[y_counts == y_max]

print("Most frequent value(s) in y:", y_frequent)
for value in y_frequent:
    print("Indices:", np.where(y == value)[0])

Reversed array: [5 4 6 3 2 1]
Most frequent value(s) in x: [1]
Indices: [0 5 7 8 9]
Most frequent value(s) in y: [1 3]
Indices: [0 1 2]
Indices: [4 8 9]


Question-3

In [3]:
import numpy as np

arr = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])

print(arr[0, 1])
print(arr[2, 0])

20
70


Question-4

In [5]:
import numpy as np

Aakriti = np.linspace(10, 100, 25)

print("Array:", Harshita)
print("Dimensions:", Harshita.ndim)
print("Shape:", Harshita.shape)
print("Total elements:", Harshita.size)
print("Data type:", Harshita.dtype)
print("Total bytes:", Harshita.nbytes)

transpose = Harshita.reshape(25, 1)
print("Transpose using reshape():")
print(transpose)

print("Transpose using T:")
print(Harshita.T)

Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions: 1
Shape: (25,)
Total elements: 25
Data type: float64
Total bytes: 200
Transpose using reshape():
[[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]
Transpose using T:
[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]


Question-5

In [6]:
import numpy as np

ucs420_Harshita = np.array([[10, 20, 30, 40],
                             [50, 60, 70, 80],
                             [90, 15, 20, 35]])

print("Mean:", np.mean(ucs420_Harshita))
print("Median:", np.median(ucs420_Harshita))
print("Maximum:", np.max(ucs420_Harshita))
print("Minimum:", np.min(ucs420_Harshita))
print("Unique elements:", np.unique(ucs420_Harshita))

reshaped_ucs420_Harshita = ucs420_Harshita.reshape(4, 3)
print("Reshaped array:")
print(reshaped_ucs420_Harsh)

resized_ucs420_Aakriti = np.resize(ucs420_Aakriti, (2, 3))
print("Resized array:")
print(resized_ucs420_Aakriti)

Mean: 43.333333333333336
Median: 37.5
Maximum: 90
Minimum: 10
Unique elements: [10 15 20 30 35 40 50 60 70 80 90]
Reshaped array:
[[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]
Resized array:
[[10 20 30]
 [40 50 60]]
