Q1. Sensor Readings

In [1]:
import numpy as np

temperature = np.array([25, 28, 31, 35, 38, 27, 33, 40])


corrected_temperature = temperature + 2
print("Corrected temperatures:", corrected_temperature)


fahrenheit = (9/5) * corrected_temperature + 32
print("Temperature in Fahrenheit:", fahrenheit)


greater_than_32 = corrected_temperature[corrected_temperature > 32]
print("Readings greater than 32°C:", greater_than_32)


count = np.sum(corrected_temperature > 32)
print("Number of readings exceeding 32°C:", count)

Corrected temperatures: [27 30 33 37 40 29 35 42]
Temperature in Fahrenheit: [ 80.6  86.   91.4  98.6 104.   84.2  95.  107.6]
Readings greater than 32°C: [33 37 40 35 42]
Number of readings exceeding 32°C: 5


In [7]:
#que 3
import numpy as np

# a
original = np.array([1, 2, 3, 4, 5, 6])
print("Original:", original)

# b
subset = original[1:5]
print("Subset:", subset)

# c
subset[0] = 999

print("After modifying subset:")
print("Original:", original)
print("Subset:", subset)

# d
copied = original[1:5].copy()

copied[0] = 500

print("\nAfter modifying copied array:")
print("Original:", original)
print("Copied:", copied)

# e
matrix = np.arange(1, 13).reshape(3, 4)

print("\n3 x 4 Matrix:")
print(matrix)

# f

# First row
first_row = matrix[0]
print("\nFirst row:", first_row)

# Last row
last_row = matrix[-1]
print("Last row:", last_row)

# Second column
second_column = matrix[:, 1]
print("Second column:", second_column)

# Rows 1-2 and columns 2-3
selected = matrix[1:3, 2:4]
print("Rows 1-2 and columns 2-3:")
print(selected)

# g
flat_array = matrix.flatten()
ravel_array = matrix.ravel()

print("\nUsing flatten():", flat_array)
print("Using ravel():", ravel_array)

# h
ravel_array[0] = 1000

print("\nAfter modifying ravel:")
print("Ravel array:", ravel_array)
print("Original matrix:")
print(matrix)

# i
flat_array[1] = 2000

print("\nAfter modifying flatten:")
print("Flatten array:", flat_array)
print("Original matrix:")
print(matrix)

# j
print("\nMatrix properties:")
print("Shape:", matrix.shape)
print("Dimensions:", matrix.ndim)
print("Size:", matrix.size)
print("Data type:", matrix.dtype)

Original: [1 2 3 4 5 6]
Subset: [2 3 4 5]
After modifying subset:
Original: [  1 999   3   4   5   6]
Subset: [999   3   4   5]

After modifying copied array:
Original: [  1 999   3   4   5   6]
Copied: [500   3   4   5]

3 x 4 Matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

First row: [1 2 3 4]
Last row: [ 9 10 11 12]
Second column: [ 2  6 10]
Rows 1-2 and columns 2-3:
[[ 7  8]
 [11 12]]

Using flatten(): [ 1  2  3  4  5  6  7  8  9 10 11 12]
Using ravel(): [ 1  2  3  4  5  6  7  8  9 10 11 12]

After modifying ravel:
Ravel array: [1000    2    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

After modifying flatten:
Flatten array: [   1 2000    3    4    5    6    7    8    9   10   11   12]
Original matrix:
[[1000    2    3    4]
 [   5    6    7    8]
 [   9   10   11   12]]

Matrix properties:
Shape: (3, 4)
Dimensions: 2
Size: 12
Data type: int64


In [6]:
#que 2
import numpy as np

steps = np.array([
    [5000, 6200, 7100],
    [8000, 7500, 9000],
    [4500, 5100, 4800],
    [9000, 8500, 9500]
])

# a
total = np.sum(steps)
print("Total steps:", total)

# b
mean = np.mean(steps)
print("Mean steps:", mean)

# c
maximum = np.max(steps)
minimum = np.min(steps)
print("Maximum steps:", maximum)
print("Minimum steps:", minimum)

# d
day_total = np.sum(steps, axis=0)
print("Total steps for each day:", day_total)

# e
user_total = np.sum(steps, axis=1)
print("Total steps for each user:", user_total)

# f
position = np.unravel_index(np.argmax(steps), steps.shape)
print("Position of maximum value:", position)

Total steps: 84200
Mean steps: 7016.666666666667
Maximum steps: 9500
Minimum steps: 4500
Total steps for each day: [26500 27300 30400]
Total steps for each user: [18300 24500 14400 27000]
Position of maximum value: (np.int64(3), np.int64(2))
